"""Generated byte/estimator parity gate; no camera media may be opened here."""
import argparse
from dataclasses import replace
import hashlib
import json
from pathlib import Path
import sys
import time

HERE = Path(__file__).resolve().parent
RUNTIME = Path('/tmp/seaqr_exact_v9_rS2LFx')
sys.path[:0] = [str(HERE), str(RUNTIME), str(RUNTIME/'scripts')]
import cv2
import numpy as np
import vpi
from motion_front_v15 import DirectMotionV15
from motion_front_pixels_v15 import proxy_pixels, logical_identity, FrontLibrary
from motion_reuse_v12 import ReuseMotionV12
from check_raw16_motion_controls import cases, frame, texture
from profile_raw16_efficiency import compact, sha
from tiny_target.motion import pva_pyrlk as pva
from tiny_target.motion import GlobalMotionConfig, fit_global_motion, PvaMotionError
from tiny_target.types import Frame, TimestampSource, Discontinuity

CONFIG = RUNTIME/'configs/evaluation/raw16_motion_v6.json'


def write(path, value):
    with path.open('x') as handle:
        json.dump(value, handle, indent=2, allow_nan=False)


def outcome(estimator, a, b, fitter):
    start = time.perf_counter()
    try:
        pairs = estimator.estimate(a, b)
    except PvaMotionError as exc:
        if any(s in str(exc) for s in ('zero features', 'No finite in-bounds')):
            return dict(identity={'unavailable': str(exc)}, logical={'unavailable': str(exc)},
                        accepted=False, estimator_ms=1000*(time.perf_counter()-start), substage_ms={}, shift=None)
        raise
    elapsed = 1000*(time.perf_counter()-start)
    fit = fit_global_motion(pairs, fitter, execution='translation_batched_exact_v1')
    identity = compact(dict(pairs=pairs, fit=fit))
    return dict(identity=identity, logical=logical_identity(identity), accepted=fit.accepted,
                shift=fit.previous_to_current_matrix[:2, 2].tolist() if fit.previous_to_current_matrix is not None else None,
                estimator_ms=elapsed, substage_ms=pairs.timings_ms)


def generated_sequence(depth, shape, kind):
    h, w = shape
    tile = texture(75316, bright=True)
    base = np.ascontiguousarray(np.tile(tile, ((h+959)//960, (w+1279)//1280))[:h, :w])
    rng = np.random.default_rng(753166)
    frames = []
    for i in range(8 if kind == 'recovery' else 6):
        work = cv2.warpAffine(base.astype(np.float32),
                              np.array([[1, 0, i*1.5], [0, 1, -i*.75]], np.float32),
                              (w, h), flags=cv2.INTER_CUBIC, borderMode=cv2.BORDER_REFLECT_101)
        image = np.clip(np.rint(work), 0, 65535).astype(np.uint16)
        if kind == 'recovery' and i in (2, 3):
            image = rng.integers(8000, 26000, shape, dtype=np.uint16)
        if kind == 'recovery' and i == 4:
            image[:] = 12000
        if depth == 8:
            image = np.clip(np.rint(image.astype(np.float32)/128), 0, 255).astype(np.uint8)
        mask = np.ones(shape, bool)
        mask[:8] = False
        mask[-8:] = False
        frames.append(Frame(image, i*100000000, i, 'v15-generated-'+kind, depth,
                            TimestampSource.MANIFEST, valid_mask=mask))
    if kind == 'invalidation':
        frames[2] = replace(frames[2], discontinuities=(Discontinuity.CHUNK_BOUNDARY,))
        for i in range(3, len(frames)):
            frames[i] = replace(frames[i], source_id='v15-new-source', frame_index=i+1)
    return frames


def run(output):
    if output.exists():
        raise FileExistsError(output)
    cv2.setNumThreads(2)
    cfg = json.loads(CONFIG.read_text())
    motion = pva.PvaMotionConfig.from_mapping(cfg['motion'])
    library = FrontLibrary(HERE/'build/libmotion_front_v15.so')
    fitter = GlobalMotionConfig.from_mapping(cfg['global_motion'])
    record = dict(schema='seaqr.motion-front-v15-generated.v1', real_media_read=False,
                  production_approved=False, pipeline_benchmark=False, passed=False,
                  source_sha256={p: sha(HERE/p) for p in
                                 ('motion_front_v15.py', 'motion_front_pixels_v15.py', 'motion_reuse_v12.py', 'check_motion_front_v15.py', 'motion_front_v15.cpp', 'build_motion_front_v15.py')},
                  library_sha256=sha(HERE/'build/libmotion_front_v15.so'),
                  config_sha256=sha(CONFIG), runtime_motion_sha256=sha(Path(pva.__file__)),
                  pixels=[], independent=[], sequences=[], timings=[], error=None)
    try:
        stream = vpi.Stream(vpi.Backend.CUDA)
        for depth in (8, 9, 10, 12, 14, 16):
            for mask_mode in ('all', 'none', 'pattern'):
                for phase in range(4):
                    image = (np.arange(65536, dtype=np.uint32).reshape(256, 256) % (1 << depth)).astype(np.uint8 if depth == 8 else np.uint16)
                    image = np.roll(image, (phase//2, phase % 2), axis=(0, 1))
                    mask = None if mask_mode == 'all' else np.zeros(image.shape, bool) if mask_mode == 'none' else image % 7 != 0
                    f = Frame(image, 0, 0, 'v15-codes', depth, TimestampSource.MANIFEST, valid_mask=mask)
                    before = f.pixel_sha256()
                    mapped = pva._feature_pixels(f, 'raw_robust_u16_v1')
                    wrapped = vpi.asimage(mapped, vpi.Format.U8 if depth == 8 else vpi.Format.U16)
                    resized = wrapped.rescale((128, 128), backend=vpi.Backend.CUDA, stream=stream)
                    stream.sync()
                    with resized.rlock_cpu() as data:
                        expected = np.array(data, copy=True)
                    actual = proxy_pixels(f, 'raw_robust_u16_v1', library=library)
                    exact = actual.dtype == expected.dtype and actual.shape == expected.shape and actual.tobytes() == expected.tobytes()
                    record['pixels'].append(dict(depth=depth, mask=mask_mode, phase=phase, exact=exact,
                                                 input_unchanged=before == f.pixel_sha256(),
                                                 different_pixels=int(np.count_nonzero(actual != expected))))
                    if not exact or before != f.pixel_sha256():
                        raise AssertionError('Installed VPI rescale does not equal fused half-linear preparation')
        print('72 installed-VPI pixel checks passed', flush=True)
        rng = np.random.default_rng(151616)
        for depth in (8, 16):
            for scene in ('range', 'dim', 'flat'):
                dtype = np.uint8 if depth == 8 else np.uint16
                maximum = (256 if depth == 8 else 65536) if scene == 'range' else (32 if depth == 8 else 2048)
                image = rng.integers(0, maximum, (3190, 4784), dtype=dtype)
                if scene == 'flat':
                    image[:] = maximum//2
                mask = np.ones(image.shape, bool)
                mask[16:24, 32:48] = False
                f = Frame(image, 0, 0, 'v15-native-'+scene, depth, TimestampSource.MANIFEST, valid_mask=mask)
                before = f.pixel_sha256()
                mapped = pva._feature_pixels(f, 'raw_robust_u16_v1')
                wrapped = vpi.asimage(mapped, vpi.Format.U8 if depth == 8 else vpi.Format.U16)
                resized = wrapped.rescale((2392, 1595), backend=vpi.Backend.CUDA, stream=stream)
                stream.sync()
                with resized.rlock_cpu() as data:
                    expected = np.array(data, copy=True)
                actual = proxy_pixels(f, 'raw_robust_u16_v1', library=library)
                exact = actual.dtype == expected.dtype and actual.shape == expected.shape and actual.tobytes() == expected.tobytes()
                record['pixels'].append(dict(depth=depth, native_scene=scene, exact=exact,
                                             input_unchanged=before == f.pixel_sha256(),
                                             different_pixels=int(np.count_nonzero(actual != expected))))
                if not exact or before != f.pixel_sha256():
                    raise AssertionError('Native motion image pixel mismatch')
        print('6 native installed-VPI pixel checks passed', flush=True)
        for seed in (75316, 75317, 75318, 75319):
            reference, candidate = ReuseMotionV12(motion), DirectMotionV15(motion)
            try:
                for name, previous, current, truth in cases(seed):
                    a, b = frame(previous, 0, name), frame(current, 1, name)
                    hashes = [a.pixel_sha256(), b.pixel_sha256()]
                    left, right = outcome(reference, a, b, fitter), outcome(candidate, a, b, fitter)
                    decisions = [(r['accepted'] and np.linalg.norm(np.array(r['shift'])-truth) <= .35)
                                 if truth is not None else not r['accepted'] for r in (left, right)]
                    exact = left['logical'] == right['logical']
                    record['independent'].append(dict(seed=seed, case=name, exact=exact,
                                                     expected_decisions=bool(all(decisions)),
                                                     reference=left, candidate=right))
                    if not exact or not all(decisions) or hashes != [a.pixel_sha256(), b.pixel_sha256()]:
                        raise AssertionError('Generated motion point/fit or expected decision changed')
            finally:
                reference.close()
                candidate.close()
            print('independent seed', seed, 'passed', flush=True)
        for shape in ((960, 1280), (3190, 4784)):
            for depth in (8, 16):
                for kind in ('smooth', 'recovery', 'invalidation', 'reordered'):
                    frames = generated_sequence(depth, shape, kind)
                    ids = [(0, 1), (1, 2), (0, 1), (0, 1), (2, 3), (3, 4)] if kind == 'reordered' else [(i-1, i) for i in range(1, len(frames))]
                    original = [f.pixel_sha256() for f in frames]
                    reference, candidate = ReuseMotionV12(motion), DirectMotionV15(motion)
                    rows = []
                    try:
                        for i, j in ids:
                            a, b = frames[i], frames[j]
                            left, right = outcome(reference, a, b, fitter), outcome(candidate, a, b, fitter)
                            exact = left['logical'] == right['logical']
                            rows.append(dict(pair=[i, j], exact=exact, reference=left, candidate=right))
                            if not exact:
                                raise AssertionError('Sequence point/fit identities changed')
                        if kind in ('smooth', 'recovery') and not rows[-1]['candidate']['accepted']:
                            raise AssertionError('Clean sequence did not recover')
                        if original != [f.pixel_sha256() for f in frames]:
                            raise AssertionError('Input frames modified')
                        record['sequences'].append(dict(shape=shape, depth=depth, kind=kind, rows=rows,
                                                       inputs_unchanged=True, hits=candidate.hits, misses=candidate.misses))
                    finally:
                        reference.close()
                        candidate.close()
                    print('sequence', shape, depth, kind, 'passed', flush=True)
        for depth in (8, 16):
            frames = generated_sequence(depth, (3190, 4784), 'smooth')
            expected = None
            for repeat in range(4):
                for mode in (('reference', 'candidate') if repeat % 2 == 0 else ('candidate', 'reference')):
                    estimator = (ReuseMotionV12 if mode == 'reference' else DirectMotionV15)(motion)
                    samples = []
                    try:
                        for i in range(1, len(frames)):
                            samples.append(outcome(estimator, frames[i-1], frames[i], fitter))
                    finally:
                        estimator.close()
                    identities = [r['logical'] for r in samples]
                    if expected is None:
                        expected = identities
                    if identities != expected:
                        raise AssertionError('Timed output mismatch')
                    record['timings'].append(dict(depth=depth, repeat=repeat, mode=mode, samples=samples))
                    print('timed', depth, repeat, mode, [round(r['estimator_ms'], 2) for r in samples], flush=True)
        record['passed'] = len(record['pixels']) == 78 and len(record['independent']) == 48 and len(record['sequences']) == 16 and len(record['timings']) == 16
    except BaseException as exc:
        record['error'] = repr(exc)
        raise
    finally:
        write(output, record)
    return 0 if record['passed'] else 1


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', type=Path, required=True)
    raise SystemExit(run(parser.parse_args().output))
