name: smoke
on:
  pull_request:
    branches: [ master, main ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install minimal deps
        run: |
          python -m pip install --upgrade pip
          pip install "ultralytics>=8.3,<9" numpy opencv-python-headless matplotlib pandas pyyaml
      - name: Import smoke test
        run: |
          python - <<'PY'
          import ultralytics, numpy, cv2, matplotlib, pandas, yaml
          print("Imports OK")
          PY
